apiVersion: apps/v1
kind: Deployment
metadata:
    name: pensioncalc-deployment
spec:
    selector:
        matchLabels:
            app: pensioncalculation
    replicas: 3
    template:
        metadata:
            labels:
                app: pensioncalculation
        spec:
            containers:
                - name: oev-pensioncalc
                  image: pensionapi:1.0.0
                  ports:
                      - containerPort: 80
        
  