version: '3'
services:
  pensioncalculationrestapi:
    image: "pensioncalculationapi:1.0.0"
    container_name: pensioncalculation
    ports:
      - 8080:8080
    environment:
          - "SPRING_PROFILES_ACTIVE=container"