apiVersion: v1
kind: Service
metadata:
    name: pensioncalc-service
spec:
    selector:
        app: pensioncalculation

    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 30001
    type: NodePort
        